# permissions for end users to view operatorredishas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorredisha-viewer-role
rules:
- apiGroups:
  - apps.operator-redis-ha.org
  resources:
  - operatorredishas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.operator-redis-ha.org
  resources:
  - operatorredishas/status
  verbs:
  - get
