---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.operator-redis-ha.org
  resources:
  - operatorredishas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.operator-redis-ha.org
  resources:
  - operatorredishas/finalizers
  verbs:
  - update
- apiGroups:
  - apps.operator-redis-ha.org
  resources:
  - operatorredishas/status
  verbs:
  - get
  - patch
  - update
